name: E2E Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run_e2e_tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Copy test environment variables
        run: cp example.env .env

      - name: Setup node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 18

      - name: Cache dependencies
        id: cache
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install --immutable

      - name: Install Playwright Browsers
        run: npx playwright install chromium --with-deps

      - name: Build apps
        run: yarn turbo run build --color --concurrency=5

      - name: Run dev server
        run: bash e2e/support/github/run-e2e-docker-env.sh

      - name: Wait for OpenMRS instance to start
        run: while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' http://localhost:8080/openmrs/login.htm)" != "200" ]]; do sleep 10; done

      - name: Run E2E tests
        run: yarn test-e2e

      - name: Stop dev server
        if: '!cancelled()'
        run: docker stop $(docker ps -a -q)

      - name: Upload report
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: '!cancelled()'
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
          overwrite: true

      - name: Capture Server Logs
        if: '!cancelled()'
        uses: jwalton/gh-docker-logs@v2
        with:
          dest: './logs'

      - name: Upload Logs as Artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: '!cancelled()'
        with:
          name: server-logs
          path: './logs'
          retention-days: 2
          overwrite: true
